version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      cgptnetwork:
        ipv4_address: 172.28.0.2

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage
    networks:
      cgptnetwork:
        ipv4_address: 172.28.0.3

  streamlit:
    container_name: compliancegpt_streamlit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      cgptnetwork:
        ipv4_address: 172.28.0.4

volumes:
  ollama:
  qdrant:

networks:
  cgptnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

